version: "3.8"

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: ghcr.io/sbkubric/supervacancies-django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ghcr.io/sbkubric/supervacancies-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: ghcr.io/sbkubric/supervacancies-traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:6

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    image: ghcr.io/sbkubric/supervacancies-traefik
    env_file:
      - ./.envs/.production/.django
    volumes:
      - postgres_data_backups:/backups:z
