# Generated by Django 4.1.7 on 2023-02-17 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_job_cv_job_vacancy_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="job",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="updated_by",
        ),
    ]
