# Generated by Django 4.1.7 on 2023-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0003_remove_job_created_at_remove_job_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cv_file",
            field=models.FileField(
                null=True, upload_to="cv", verbose_name="Your CV file"
            ),
        ),
    ]
