# Generated by Django 4.1.7 on 2023-02-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0004_application_cv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalentity",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Visible"), (1, "In archive")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "id"], name="vacancies_application_status"
            ),
        ),
        migrations.AddIndex(
            model_name="cv",
            index=models.Index(fields=["status", "id"], name="vacancies_cv_status"),
        ),
        migrations.AddIndex(
            model_name="legalentity",
            index=models.Index(
                fields=["status", "id"], name="vacancies_legalentity_status"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["status", "id"], name="vacancies_vacancy_status"
            ),
        ),
    ]
