# Generated by Django 4.1.7 on 2023-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0005_legalentity_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="cv_file",
            field=models.FileField(null=True, upload_to="", verbose_name="CV file"),
        ),
    ]
