# Generated by Django 4.1.7 on 2023-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0007_alter_cv_cv_file_alter_cv_experience_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="state",
            field=models.PositiveBigIntegerField(
                choices=[
                    (0, "Awaits response"),
                    (1, "Empoyer accepted application"),
                    (2, "Employer rejected application"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Visible"), (1, "In archive")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["state", "status", "id"], name="vacancies_application_state"
            ),
        ),
    ]
