# Generated by Django 4.1.7 on 2023-02-17 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("access_employer_area", "Is user an employer?"),
                    ("access_applicant_area", "Is user an applicant?"),
                ]
            },
        ),
    ]
