# Generated by Django 4.1.7 on 2023-02-15 22:00

from django.db import migrations
import supervacancies.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", supervacancies.users.models.ApplicantUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmployerUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", supervacancies.users.models.EmployerUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("access_employer_area", "Is user an employer?"),
                    ("access_applicant_area", "Is user an applicant?"),
                ]
            },
        ),
    ]
